// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCssOJxPVM6TXRpJK9DZ38RFcXO4xKNioY',
    appId: '1:398323828839:web:f927deb7a8fee5b80b2cc2',
    messagingSenderId: '398323828839',
    projectId: 'ietp-2d1a6',
    authDomain: 'ietp-2d1a6.firebaseapp.com',
    storageBucket: 'ietp-2d1a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHu81F0HNzKhrYspA0WP3G9C_j_NamMYg',
    appId: '1:398323828839:android:9f1581a1d583b5c80b2cc2',
    messagingSenderId: '398323828839',
    projectId: 'ietp-2d1a6',
    storageBucket: 'ietp-2d1a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaFNpOktPGam4aW3MLlcS0N4GEewMeB4Y',
    appId: '1:398323828839:ios:9fda738247d2b6e00b2cc2',
    messagingSenderId: '398323828839',
    projectId: 'ietp-2d1a6',
    storageBucket: 'ietp-2d1a6.firebasestorage.app',
    iosBundleId: 'com.example.ietp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaFNpOktPGam4aW3MLlcS0N4GEewMeB4Y',
    appId: '1:398323828839:ios:9fda738247d2b6e00b2cc2',
    messagingSenderId: '398323828839',
    projectId: 'ietp-2d1a6',
    storageBucket: 'ietp-2d1a6.firebasestorage.app',
    iosBundleId: 'com.example.ietp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCssOJxPVM6TXRpJK9DZ38RFcXO4xKNioY',
    appId: '1:398323828839:web:96eae4322fdf05260b2cc2',
    messagingSenderId: '398323828839',
    projectId: 'ietp-2d1a6',
    authDomain: 'ietp-2d1a6.firebaseapp.com',
    storageBucket: 'ietp-2d1a6.firebasestorage.app',
  );
}
